### ISSUE TITLE
Just makes a copy of the demo.gif

### ISSUE THREAD

**Issue by tjt263** [pettarin/asciicast2gif#2]
Hi, i tried: `~/asciicast2gif/asciicast2gif ~/example.json ~/example.gif`. 
It just seems to, either: 

1. Copy `~/asciicast2gif/gifs/demo.gif` to `~/example.gif`; or 
2. Parse `~/asciicast2gif/gifs/demo.json`, instead of `~/example.json`.
           (or `~/asciicast2gif/demo.json`).

Not sure what i did wrong here.

**Comment by pettarin** [comment]
Hi,

have you tried cd into the directory asciicast2gif and running from 
there? E.g.:

$ cd /tmp
$ git clone https://github.com/pettarin/asciicast2gif.git
$ cd asciicast2gif
$ ./asciicast2gif demo.json
$ # file demo.json.gif has been created

I might have been sloppy in terms of supporting running the script from 
any directory --- I always use it cd-ing into the project root directory.

HTH,

AP

**Comment by tjt263** [comment]
@pettarin 
Ah, I just noticed that you mentioned it in the readme file.
After reading about that; I thought that would fix it, but same thing.
The problem with that example that you gave, is that it's performing the operation on `./demo.json` regardless of the input specified. 

For instance:
<pre><code>cd ./asciicast2gif/                       #current working directory
cp ../example.json ./                     #copy to current directory
rm demo.json                              #remove(for demonstration)

./asciicast2gif <b>example.json</b> example.gif  #specify JSON in & GIF out

[INFO] Starting Python 2 SimpleHTTPServer on port 8000
[INFO] Temporary directory is /tmp/asciicast2gif.8HfD2UnI
[ERRO] Error transferring http://localhost:8000/<b>demo.json</b> -server replied: File not found
[INFO] error fetching asciicast file:
[INFO] ({:status 404, :status-text "File not found", :failure :error, :response
"&lt;head&gt;\n&lt;title&gt;Error response&lt;/title&gt;\n&lt;/head&gt;\n&lt;body&gt;\n&lt;h1&gt;Error response&lt;/h1&gt;
&lt;p&gt;Error code 404.\n&lt;p&gt;Message: File not found.\n&lt;p&gt;Error code explanation: 404 
= Nothing matches the given URI.\n&lt;/body&gt;\n"})
</pre></code>

**Comment by pettarin** [comment]
Hi,

sorry, but I cannot replicate the issue. On my machine:

$ cd /tmp
$ git clone https://github.com/pettarin/asciicast2gif.git
$ cd asciicast2gif
$ mv demo.js foo.js
$ ./asciicast2gif foo.js
[INFO] Starting Python 2 SimpleHTTPServer on port 8000
[INFO] Temporary directory is /tmp/asciicast2gif.lEMXH8It
[INFO]   Progress: 7%
[INFO]   Progress: 14%
[INFO]   Progress: 21%
[INFO]   Progress: 30%
[INFO]   Progress: 37%
[INFO]   Progress: 44%
[INFO]   Progress: 53%
[INFO]   Progress: 60%
[INFO]   Progress: 67%
[INFO]   Progress: 76%
[INFO]   Progress: 83%
[INFO]   Progress: 90%
[INFO]   Progress: 100%
[INFO] Capture completed
[INFO] Terminating simple HTTP server
[INFO] Generating GIF...
[INFO] Created /tmp/asciicast2gif/foo.js.gif

(same if I use example.js instead of foo.js or if I specify the GIF file 
name explicitly)

It might be a problem with bashisms. If you use another shell and you 
want to polish the script, feel free to go ahead.

(It is a really old project, and the code looks quite lame to me now...)

AP

**Comment by tjt263** [comment]
It's not perfect, but it's not too bad.
I have fixed up a bunch of things.
Going to send a pull request, but not sure why this isn't working for me.
Must be a problem with the packages on my system.
Thanks for taking the time.

**Comment by pettarin** [comment]
Closing, as I just pushed a new version, with bashisms (hopefully) removed.
